Repository keichi/cuEDM, pull requests merged in 2020-01, with the labels that each got.

#61 Write cross mapping results to file
  CMakeLists.txt
  README.md
  src/cross_mapping_bench.cc
  src/dataframe.cc
  src/dataframe.h
Labels: enhancement

#64 Fix hanging bug in MPIMaster/Worker
  src/mpi_master.cc
  src/mpi_master.h
  src/mpi_worker.cc
Labels: bug

#63 Apply MPI for cross mapping
  CMakeLists.txt
  src/cross_mapping_mpi_bench.cc
Labels: enhancement

#65 Improve scalability of MPI master
  src/mpi_master.cc
Labels: performance

#66 Improve load balancing between threads in k-NN and cross mapping
  src/cross_mapping_cpu.cc
  src/cross_mapping_gpu.cc
Labels: performance

#73 Add option to select HDF5 dataset
  CMakeLists.txt
  scripts/csv2h5.py
  src/cross_mapping.h
  src/cross_mapping_bench.cc
  src/cross_mapping_mpi_bench.cc
  src/data_frame.cc
  src/data_frame.h
  src/embedding_dim.h
  src/knn_bench.cc
  src/nearest_neighbors.h
  src/nearest_neighbors_gpu.h
  src/simplex.h
  src/simplex_bench.cc
  src/simplex_cpu.h
  src/simplex_gpu.h
  src/simplex_mpi_bench.cc
  src/stats.h
  test/cross_mapping_test.cc
  test/knn_test.cc
  test/simplex_test.cc
Labels: enhancement
